# Generated by Django 5.1.6 on 2025-02-12 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador del sistema'), ('store_admin', 'Administrador de tienda'), ('seller', 'Vendedor'), ('customer', 'Cliente')], default='customer', max_length=20, verbose_name='Rol'),
        ),
    ]
