# Generated by Django 5.1.6 on 2025-03-14 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_options_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('superuser', 'Superusuario'), ('admin', 'Administrador'), ('store_admin', 'Administrador de tienda'), ('seller', 'Vendedor de tienda'), ('customer', 'Cliente')], default='customer', max_length=20, verbose_name='Rol'),
        ),
    ]
