# Generated by Django 5.1.6 on 2025-02-12 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_category_alter_product_options_alter_product_barcode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='min_stock',
            field=models.PositiveIntegerField(default=5, verbose_name='Stock mínimo para alerta'),
        ),
    ]
