# Generated by Django 5.1.6 on 2025-02-12 20:35

import django.db.models.deletion
import store.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_stockmovement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockmovement',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='default_product.jpg', null=True, upload_to=store.models.product_image_path, verbose_name='Imagen del producto'),
        ),
        migrations.AlterField(
            model_name='category',
            name='min_stock',
            field=models.PositiveIntegerField(default=1, verbose_name='Stock mínimo antes de alerta'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Nombre de categoría'),
        ),
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Código de barras'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='store.category', verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(verbose_name='Stock disponible'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='change',
            field=models.IntegerField(verbose_name='Cambio en stock'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='reason',
            field=models.CharField(max_length=255, verbose_name='Razón de cambio'),
        ),
    ]
