# Generated by Django 5.1.6 on 2025-02-13 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_stockmovement_options_product_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
    ]
