# Generated by Django 5.1.6 on 2025-02-12 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0002_alter_invoiceitem_cost_per_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('procesada', 'Procesada'), ('anulada', 'Anulada')], default='pendiente', max_length=10, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='cost_per_item',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Costo unitario'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Cantidad'),
        ),
    ]
