# Generated by Django 5.1.6 on 2025-02-12 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0005_alter_invoice_invoice_number_alter_invoice_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=20, unique=True, verbose_name='Número de factura'),
        ),
    ]
