# Generated by Django 5.1.6 on 2025-02-13 22:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('purchases', '0006_alter_invoice_invoice_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='sales_point',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='inventory.salespoint', verbose_name='Punto de venta'),
            preserve_default=False,
        ),
    ]
