# Generated by Django 5.1.6 on 2025-02-14 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('purchases', '0007_invoice_sales_point'),
        ('store', '0007_delete_stockmovement'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('reason', models.CharField(max_length=255, verbose_name='Motivo del retorno')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de devolución')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='purchases.invoice', verbose_name='Factura')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product', verbose_name='Producto')),
                ('sales_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.salespoint', verbose_name='Punto de venta')),
            ],
        ),
    ]
