# Generated by Django 5.1.6 on 2025-02-22 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_stock_reserved_quantity_alter_stock_sales_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='sales_point',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='inventory.salespoint', verbose_name='Punto de venta'),
        ),
    ]
