# Generated by Django 4.2.18 on 2025-02-05 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0003_product_sku_salespoint_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=50, verbose_name='Apellido')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('address', models.CharField(max_length=250, verbose_name='Dirección')),
                ('postal_code', models.CharField(max_length=20, verbose_name='Código postal')),
                ('city', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'En proceso'), ('shipped', 'Enviado'), ('delivered', 'Entregado'), ('cancelled', 'Cancelado')], default='pending', max_length=20, verbose_name='Estado')),
                ('note', models.TextField(blank=True, verbose_name='Nota adicional')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Cantidad')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='Pedido')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='catalog.product', verbose_name='Producto')),
            ],
        ),
    ]
