# Generated by Gemini
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='delivery_time',
            field=models.CharField(choices=[('Entrega inmediata', 'Entrega inmediata'), ('Entrega en 5-7 días', 'Entrega en 5-7 días')], default='Entrega inmediata', max_length=20, verbose_name='Tiempo de entrega'),
        ),
    ]
