# Generated by Gemini
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_add_delivery_time_to_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Tarjeta'), ('mercado_pago', 'Mercado Pago'), ('cash', 'Efectivo')], default='card', max_length=20, verbose_name='Método de pago'),
        ),
    ]
