# Generated by Django 5.2 on 2025-09-23 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_stock_sales_point'),
        ('orders', '0005_add_payment_method_to_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='sales_point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='inventory.salespoint'),
        ),
    ]
