# Generated by Django 5.2 on 2025-09-23 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_orderitem_sales_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_cost_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Себестоимость заказа'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Себестоимость в момент продажи'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Цена в момент продажи'),
        ),
    ]
