# Generated by Django 5.2 on 2025-09-23 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20250923_1854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_cost_price',
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена в момент продажи'),
        ),
    ]
