# Generated by Django 5.2 on 2025-09-23 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_remove_order_total_cost_price_alter_orderitem_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En proceso'), ('enviado', 'Enviado'), ('completado', 'Completado'), ('cancelado', 'Cancelado'), ('fallido', 'Fallido')], default='pendiente', max_length=20, verbose_name='Estado'),
        ),
    ]
