# Generated by Django 5.2 on 2025-09-24 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_cost_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Costo total'),
        ),
    ]
